name: Build FW
on: push
jobs:
  build-firmware:
    runs-on: ubuntu-latest
    container:
            image: vlastik/avr-gcc:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set Version Variable
        run: echo "FW_VERSION=${GITHUB_REF#refs/*/}" | sed -r 's,/,-,g' >> $GITHUB_ENV

      - name: Build the Firmware
        run: make FW_VERSION=${{ env.FW_VERSION }}

      - name: Save the Firmware Binaries
        uses: actions/upload-artifact@v4
        with:
          name: LTO-BMS-${{ env.FW_VERSION }}
          path: |
            build/*.bin
            build/*.hex
            build/*.elf
          if-no-files-found: error

  build-datasheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: datasheet
          root_file: datasheet.tex

      - name: Save the datasheet PDF
        uses: actions/upload-artifact@v4
        with:
          name: LTO-BMS-datasheet
          path: datasheet/datasheet.pdf
          if-no-files-found: error

  create-release:
    name: Create FW Release
    runs-on: ubuntu-latest
    needs: [build-firmware, build-datasheet]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Set Version Variable
        run: echo "FW_VERSION=${GITHUB_REF#refs/*/}" | sed -r 's,/,-,g' >> $GITHUB_ENV

      - name: Get FW Files
        uses: actions/download-artifact@v4
        with:
          name: LTO-BMS-${{ env.FW_VERSION }}

      - name: Get Datasheet Files
        uses: actions/download-artifact@v4
        with:
          name: LTO-BMS-datasheet

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: LTO-BMS ${{ env.FW_VERSION }}
          draft: false
          fail_on_unmatched_files: true
          files: |
            ./*.hex
            ./*.pdf
